### ISSUE TITLE
Can Ark replace `languageserver` in VS Code workflow?

### ISSUE THREAD

**Issue by AdaemmerP** [posit-dev/ark#637]
Thanks for this great project! 

Does Ark already work as a replacement for `languageserver` or other components within VS Code as outlined in this workflow: https://code.visualstudio.com/docs/languages/r ? In particular, does it work in Code server? If not, how will Ark work within VS Code, apart from Jupyter Notebooks?

**Comment by lionel-** [comment]
Unfortunately this is not currently possible. But we do have plans to make the LSP independent from the Jupyter kernel.
